name: owlets
description: Wallet manager and logging app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  objectx: ^1.0.0+1-dev
  intl: ^0.18.1
  owlet_flutter:
    path: ../owlet-flutter
  google_fonts: ^6.0.0
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.9.0
  theme_tailor_annotation: ^2.0.0
  get_it: ^7.6.4
  injectable: ^2.3.0
  built_value: ^8.6.2
  built_collection: ^5.1.1
  formz: ^0.6.1
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  rowlet:
    path: ../rowlet
  owlet_base:
    path: ../owlet-base

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  owlet_lints: ^3.0.0
  flutter_gen_runner: ^5.3.1
  copy_with_extension_gen: ^5.0.4
  theme_tailor: ^2.0.0
  built_value_generator: ^8.6.2
  injectable_generator: ^2.4.0

dependency_overrides:
  objectx:
    path: ../objectx

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: false
  assets:
    - assets/image/


flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  outputs:
    # Optional
    # Set to true if you want this package to be a package dependency
    # See: https://flutter.dev/docs/development/ui/assets-and-images#from-packages
    package_parameter_enabled: false
    style: dot-delimiter
    class_name: Assets
